### PR TITLE
Support for manipulating request and response body

### PR DESCRIPTION
**Pull request by kennethmyhra**
* Added callbacks that allows manipulation of the request and response
  stream
* See issue #478 for more information

### CODE REVIEW

**Comment by ewoutkramer** [comment]
Anyway, maybe we can piggyback on the new pipeline capabilities in the HttpClient. I am still getting updated on that new class, so I don't know yet!

**Comment by kennethmyhra** [comment]
Agree, didn't look into it in detail earlier, but I see now that it's the same interface that's used on the server side and it should therefore work quite similar.

**Comment by ewoutkramer** [comment]
@kennethmyhra -- oops, I never submitted my review on this PR....Is this PR still of interest to you? (the new client written in #535 will actually fix this is a more elegant way, because of the new .NET Core webclient used).

**Comment by kennethmyhra** [comment]
@ewoutkramer I am happy with the solution that the .NET Core WebClient gives us in PR #507.

**Pull request closed without merging**
