### PR TITLE
Added to ModelInfo AddToModelInfo method

### PR DESCRIPTION
**Pull request by marcocaminiti**
the method AddToModelInfo allow to manage custom fhir resource with BaseFhirParser

### CODE REVIEW

**Comment by ewoutkramer** [comment]
This will fix serialization and deserialization - but everything in the specification library (and probably more) like validation and snapshot generation will not work, even if you would create additional StructureDefinitions for the new types.  This is due to the fact that the FhirKnownTypes enumeration cannot be expanded without regenerating the source code - and quite some code depends statically on that enumeration.

I don't mind thinking about how to make this more flexible, but are reluctant to pull a partial solution.....

**Comment by kfrancis** [comment]
@ewoutkramer Do you mean how SupportedResources is generated when that static T4 template is executed?

**Comment by brianpos** [comment]
You can do this stuff locally in your own branch/build.
Issue for me is no one outside your lib can work with the resource, or know what to do when they see it.
I wouldn't like this in the core lib. It doesn't improve standard interop.

**Comment by ewoutkramer** [comment]
I am working on a more general parsing framework for custom resources - probably extending that into the POCO parsers. For now, will not pull a partial solution.

**Pull request closed without merging**
