### PR TITLE
Feature/null reference exception bug fix

### PR DESCRIPTION
**Pull request by poadhika**
Bug fix related to following bug:
https://github.com/ewoutkramer/fhir-net-api/issues/794

### CODE REVIEW

**Comment by ewoutkramer** [comment]
Looks good, thanks!

**Comment by ewoutkramer** [comment]
Don't mind the continuous build failure - we're still tuning the publication process. Maybe @marcovisserFurore can see what's going on?  The unit-tests ran fine.

**Comment by marcovisserFurore** [comment]
> Don't mind the continuous build failure - we're still tuning the publication process. Maybe @marcovisserFurore can see what's going on? The unit-tests ran fine.

Changed Azure Devops a bit. Next Pull Requests from forks will be working fine.

**Comment by poadhika** [comment]
@ewoutkramer : Do I need to make the same change in develop-stu3? Or Will the change made in develop will propagate to develop-stu3?

**Comment by ewoutkramer** [comment]
No, you don't have to. For this kind of change that is compatible across the versions, I simply merge your changes forwards into the STU3 branch.  Quicker and easier for everyone.  Thanks for offering to do it, though.

**Pull request merged**
