### PR TITLE
Accept unknown enums when AcceptUnknownLiterals is configured.

### PR DESCRIPTION
**Pull request by tiloc**
Due to a small mismatch in specification age between FHIR .Net API and a commercial FHIR implementation there arose the need to make FHIR client a bit more tolerant when unknown enums were encountered. I have opted to enable/disable this behavior through the existing AcceptUnknownMembers switch.

### CODE REVIEW

**Comment by ewoutkramer** [comment]
That's subtle. Do we expand the notion of "expand unknown members" to "treat a known enumerated member with an incorrect value as unknown" ?

**Comment by tiloc** [comment]
True, subtle. I was seeing the "AcceptUnknownMembers" switch more as a "be tolerant" switch, as in Postel's law. I think it would be overreaching a bit to introduce additional "AcceptSomething" switches for each scenario where more tolerance is required in real-world integrations. And renaming the switch to be more generic in naming would break an existing API. So based on these considerations, I finally opted for expanding the scope of the existing switch a bit.

**Comment by ewoutkramer** [comment]
I have started a discussion about this on the FHIR Skype Implementers Chat. Are you following that chat?

**Comment by tiloc** [comment]
Not yet. Where would I find that chat? I have a Skype client.

**Comment by magohl** [comment]
I think this is the chat mentioned

https://chats.fhir.me/feeds/skype/implementers.html

I am also interested in a way to handle unknown enums.

**Comment by ewoutkramer** [comment]
Yes, this is the read-only log of the Skype chat, but if you want to participate you'd need to join that chat. Unfortunately, it's full (Microsoft limits the number of participants to 299)... But just in case, send me a Skype invite (user ewoutkramer) and I'll add you when we have capacity again.

**Comment by tiloc** [comment]
I am closing this pull request. I assume the solution for issue #167 will look considerably different.

**Comment by ewoutkramer** [comment]
Indeed, see #203!

**Pull request closed without merging**
