### PR TITLE
Add async methods to the FHIR Client

### PR DESCRIPTION
**Pull request by ricardopinedathen**
Add async methods to the FHIR Client while keeping sync methods for backward compatibility

- Update BundleExtensions with new async method
- Update FhirClient,FhirClientOperations,FhirClientSearch,Requester with new async methods, preivous sync methods retained
- Add TaskExtensions to allow easier task handling for old sync methods
- Add integration test project for async methods

### CODE REVIEW

**Comment by ewoutkramer** [comment]
Thanks! Will try to pull this this week (or else next week)

**Comment by ricardopinedathen** [comment]
Perfect, let me know if you find any issues I can solve.

**Comment by ricardopinedathen** [comment]
Fixed issues with sync methods dead-locks on gui applications. Working fine now.

**Comment by ewoutkramer** [comment]
Since you're PR, I have integrated a PR for re-enabling .NET 4.0.  Unfortunately, I have no idea how to make this work with .NET 4.0, so I have disabled that for now.  Do you know whether we can still support 4.0?

**Pull request merged**
