### PR TITLE
Feature/479 post based search

### PR DESCRIPTION
**Pull request by ewoutkramer**
Small updates to Kenneth's PR to make it work under STU3.

### CODE REVIEW

**Comment by kennethmyhra** [comment]
Tested OK. I did some minor changes to a few of the test cases, see attached patch.
[0001-Minor-fixes-to-test-cases.txt](https://github.com/ewoutkramer/fhir-net-api/files/1673230/0001-Minor-fixes-to-test-cases.txt)

**Comment by ewoutkramer** [comment]
Thanks Kenneth!

**Comment by jahansha** [comment]
I tried the Search using:  SearchUsingPost<Location>(srchParams)
I am having difficulty on binding with the Web Api parameters that are being passed. Can you please tell me the signature of the parameter for the SearchUsingPost endpoint.

Thanks

**Comment by kennethmyhra** [comment]
@jahansha 
Take a look at the server side implementation here: https://github.com/kennethmyhra/spark/blob/1befd07c225d4b7abc5d0710a6c14adf8ccadab5/src/Spark/Controllers/FhirController.cs#L144

From the documentation at http://hl7.org/fhir/search.html#2.21.1.2:
> the parameters are a series of name=[value] pairs encoded in the URL or as an application/x-www-form-urlencoded submission for a POST:
 > POST  [base]/[type]/_search{?[parameters]{&_format=[mime-type]}}

**Pull request merged**
