### PR TITLE
FhirClient Changes

### PR DESCRIPTION
**Pull request by jahansha**
Modify the **FhirClient**    to give the user the option of using Custom **HttpHeaders** with **Search** commands.  When the option is exercised, the search command will be modified so that the querystring will NOT contain any Search parameters. 
Instead a Custom HttpHeader, containing the exact querystring, will be passed.
The reason for this change is to avoid displaying Patient Health Information (PHI) within querystring.
This information passed in the querystring  is automatically logged by IIS, and this may cause a breach of confidentiality.

### CODE REVIEW

**Comment by tstolker** [comment]
Dear Jahansha,

That is a lot of work for something that is normally solved by a POST using content-type of application/www-x-form-urlencoded, which is the same as a GET but without the parameters being in the query string.
Using headers for a query is absolutely the wrong direction; as far as I can see you have create a proprietary solution for a problem that needed no solving.
I am sorry to be so harsh, but I had hoped the people responsible for the fhir client would have helped you to gude you to implement a proper solution.

Best regards,

Theo.

**Comment by jahansha** [comment]
Hi TheoThanks for your feedback. My final goal is to create a Post. The advantage of using headers is that Server will require minimal change.Please explain to me why the Header is so wrong. Thanks


Sent from Yahoo Mail for iPhone


On Tuesday, February 6, 2018, 11:21 AM, Theo Stolker <notifications@github.com> wrote:

Dear Jahansha,

That is a lot of work for something that is normally solved by a POST using content-type of application/www-x-form-urlencoded, which is the same as a GET but without the parameters being in the query string.
Using headers for a query is absolutely the wrong direction; as far as I can see you have create a proprietary solution for a problem that needed no solving.
I am sorry to be so harsh, but I had hoped the people responsible for the fhir client would have helped you to gude you to implement a proper solution.

Best regards,

Theo.

**Comment by jahansha** [comment]
Also,, the current FhirClient does not provide a post when searching. That also requires a lot of change.As all the Searches will require re-writing.The header solution will require minimal changeToBeforeWebRequest callback.Thanks


Sent from Yahoo Mail for iPhone


On Tuesday, February 6, 2018, 12:15 PM, John Arastoozad <johna@ocsx.com> wrote:

Hi TheoThanks for your feedback. My final goal is to create a Post. The advantage of using headers is that Server will require minimal change.Please explain to me why the Header is so wrong. Thanks


Sent from Yahoo Mail for iPhone


On Tuesday, February 6, 2018, 11:21 AM, Theo Stolker <notifications@github.com> wrote:

Dear Jahansha,

That is a lot of work for something that is normally solved by a POST using content-type of application/www-x-form-urlencoded, which is the same as a GET but without the parameters being in the query string.
Using headers for a query is absolutely the wrong direction; as far as I can see you have create a proprietary solution for a problem that needed no solving.
I am sorry to be so harsh, but I had hoped the people responsible for the fhir client would have helped you to gude you to implement a proper solution.

Best regards,

Theo.

**Comment by tstolker** [comment]
Hi Jahansha,

My feedback is based on the assumption that it is the best to use web standards the way they are intended. Post using content-type of application/www-x-form-urlencoded is exactly the solution intended for what you are looking for, and use in many cases where it isn’t acceptable to expose something via a URL, e.g. OAuth2 token requests, etc.

I guess I do not understand how you expect a generic FHIR server to support your custom headers. Unless the FHIR specification is changed, this remains a custom extension, which is useless for others

I don’t know how complicated it would be to change the FHIR client in order to send a search query as a POST using content-type of application/www-x-form-urlencoded, but I do know that on the server side that would be a breeze, in fact something that most web servers should support.

It would be great to discuss your requirement on Zulip and see the view of the community on this.

Best regards,

Theo

**Comment by ewoutkramer** [comment]
Hey, @jahansha, have you seen this: https://github.com/ewoutkramer/fhir-net-api/pull/526 ?  This PR has been included in the distribution a few weeks ago, and I think this solves your problem in a FHIR compatible way!

**Comment by tstolker** [comment]
Please see https://chat.fhir.org/#narrow/stream/implementers/subject/Correct.20way.20to.20implement.20API/near/125015 and the replies; this exactly addresses the same issue.

From: Theo Stolker
Sent: Tuesday, February 6, 2018 10:14 PM
To: 'ewoutkramer/fhir-net-api' <reply@reply.github.com>; ewoutkramer/fhir-net-api <fhir-net-api@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: RE: [ewoutkramer/fhir-net-api] FhirClient Changes (#535)

Hi Jahansha,

My feedback is based on the assumption that it is the best to use web standards the way they are intended. Post using content-type of application/www-x-form-urlencoded is exactly the solution intended for what you are looking for, and use in many cases where it isn’t acceptable to expose something via a URL, e.g. OAuth2 token requests, etc.

I guess I do not understand how you expect a generic FHIR server to support your custom headers. Unless the FHIR specification is changed, this remains a custom extension, which is useless for others

I don’t know how complicated it would be to change the FHIR client in order to send a search query as a POST using content-type of application/www-x-form-urlencoded, but I do know that on the server side that would be a breeze, in fact something that most web servers should support.

It would be great to discuss your requirement on Zulip and see the view of the community on this.

Best regards,

Theo

**Comment by jahansha** [comment]
Hi TheoMY goal is  to align my code with the FHIR specifications.I will be developing a POST version of the Search command.We have used the Custom HttpHeader within our internal FHIR Server.I definitely agree with you that Custom HttpHeaders deviate from the FHIR specifications.Thanks

**Comment by ewoutkramer** [comment]
Hey, @jahansha, PR #526 does indeed implement POST to do this, have a look....

**Comment by jahansha** [comment]
Hi ewout Quick question. I would like to put together a system consisting of OAuth 2.0 Secured Fhir Server & Fhir Client.. the OAuth 2.0 will provide configuration capabilities. What is your opinion?Thanks


Sent from Yahoo Mail for iPhone


On Tuesday, February 13, 2018, 9:55 AM, Ewout Kramer <notifications@github.com> wrote:


Hey, @jahansha, PR #526 does indeed implement POST to do this, have a look....

**Comment by ewoutkramer** [comment]
"I would like to put together a system consisting of OAuth 2.0 Secured Fhir Server & Fhir Client.. the OAuth 2.0 will provide configuration capabilities. What is your opinion?Thanks"

That's a broad question!  Are you wondering whether the FhirClient supports OAuth2?

**Comment by ewoutkramer** [comment]
If you are looking for a ready-made solution, you may be able to use our .NET based product Vonk: https://fire.ly/vonk/, http://docs.simplifier.net/vonk/index.html.

**Comment by ewoutkramer** [comment]
Ok, so #526 has fixed this issue neatly, closing this PR.

**Pull request closed without merging**
