### PR TITLE
Replace FhirOperationException.GetObjectData override for compatibility with low-trust environments

### PR DESCRIPTION
**Pull request by wmrutten**
See #737

### CODE REVIEW

**Comment by ewoutkramer** [comment]
@wmrutten - as I suggested in #737 and #735 - can't we just remove the override of GetObjectData?  I had never intended to do this for all custom Exceptions - and when I see your PR I am not sure I really want all that code for just defining a new exception.

@mharthoorn - is Orleans running dotnetcore or still on net framework?

**Comment by mharthoorn** [comment]
Orleans 2.x runs on .net core 2.y

**Comment by wmrutten** [comment]
@ewoutkramer sure, we can take it out. This would solve the issue at hand (support low-trust environments), but also introduce a breaking change. I've been trying to assess the actual impact.

* Pro: get rid of complexity.
* Con: drop support for exception serialization

Considerations:

* Distributed environments such as Orleans depend on exception serialization  (via `GetObjectData`) for error routing and reporting
* (also inbetween AppDomains, which are obsolete in netCore)
* `FhirOperationException` is used by the `FhirClient` to report `OperationOutcome` and `HttpStatusCode`
* netCore dropped, then re-introduced some runtime support for serialization; this is still a 'hot topic'

**Comment by wmrutten** [comment]
Removed support for serialization from `FhirOperationException` altogether.

**Comment by ewoutkramer** [comment]
@marcovisserFurore  and I have just removed build variables for doing conditional compiles for different platforms - now this PR is about to re-introduce that.  @marcovisserFurore - what do you think?

**Comment by ewoutkramer** [comment]
I have proposed the alternative #752 - which just removes the serialization. I really don't want to introduce multi-platform unit-testing and conditional compiles just for this at this moment - but I do want to help @mbaltus.

**Comment by ewoutkramer** [comment]
Done using #752.

**Pull request closed without merging**
