### PR TITLE
Mark types as serializable to enable Orleans serialization of a StructureDefinition

### PR DESCRIPTION
**Pull request by alexmarchis**
I added the serializable attribute on some Fhir.Model classes that are required by the Orleans framework in order to send a StructureDefinition serialized to clients

### CODE REVIEW

**Comment by brianpos** [comment]
Am i right ok understanding that you're interesting a for server with Orleans?
https://dotnet.github.io/orleans/Documentation/Introduction.html
That's way cool.

**Comment by brianpos** [comment]
Would you be willing to share your experience with it?

**Comment by ewoutkramer** [comment]
@brianpos: Alex works for us, we're using Orleans in Simplifier to offload expensive operations!

**Comment by brianpos** [comment]
Awesome, I'll hit you up in San Diego for some details

**Pull request merged**
