### PR TITLE
Attribute changes for serialization/deserialization with DataContractSerializer

### PR DESCRIPTION
**Pull request by gtakov**
Added the needed attributes for serialization/deserialization with DataContractSerializer.

### CODE REVIEW

**Comment by brianpos** [comment]
Can you please add some unit tests to show it in action working so we can understand what is happening, and that we can be sure as we make other changes don't break it.

**Comment by ewoutkramer** [comment]
My main problem with this PR is that it alters generated code OR adds hand-written code that should be generated, especially all the KnownType attributes, they should ideally be generated at that spot, based on information in the profiles (data definitions) in Source/.

On the one hand, the DSTU2 model won't change much anymore, but if we port this to STU3 or even Revision 4, we really need the generated code to maintain this list.

Brian, how hard would it to do that?  Georgi is not the first one who'd like Serialization to work....

**Comment by brianpos** [comment]
I can do the code generation no problems.
Just want to be sure from unit testing that we can ensure it stays working as models change, and that it will handle extensions correctly.

**Comment by ewoutkramer** [comment]
I understand that @gtakov has written a unit test now that does a full roundtrip of all resources. Which takes a considerable amount of time, of course.

**Comment by gtakov** [comment]
I have added the unit test.

**Comment by ewoutkramer** [comment]
@gtakov @brianpos  Is this still worth doing?

**Comment by ewoutkramer** [comment]
According to @brianpos, this change will not function well + we need changes to the T4 templates. Closing it.

**Comment by ewoutkramer** [comment]
I want to take another look at this.

**Pull request closed without merging**
